# Generated by Django 5.2.11 on 2026-02-10 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notification_type', models.CharField(choices=[('registration', 'Registration'), ('payment', 'Payment'), ('session_reminder', 'Session Reminder'), ('announcement', 'Announcement'), ('networking', 'Networking'), ('system', 'System'), ('feedback', 'Feedback')], max_length=50)),
                ('title_template', models.CharField(max_length=500)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('can_customize', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_registration', models.BooleanField(default=True)),
                ('email_on_session_reminder', models.BooleanField(default=True)),
                ('email_on_announcement', models.BooleanField(default=True)),
                ('email_on_networking', models.BooleanField(default=True)),
                ('email_on_feedback', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_on_session_reminder', models.BooleanField(default=True)),
                ('push_on_announcement', models.BooleanField(default=True)),
                ('push_on_networking', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_for_urgent_only', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='instant', max_length=50)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('channels', models.JSONField(default=list, help_text='JSON array of channels to send through')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=50)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('action_url', models.URLField(blank=True)),
                ('action_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx')],
            },
        ),
    ]
