# -*- coding: utf-8 -*-
"""Match.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AkJ103b2Ppf1fcXFIXt78cJy2bF23X44
"""

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Dataset (Same departments and related interests now properly mapped)
data = {
    'attendee_id': [1, 2, 3, 4, 5],
    'name': ['Ali', 'Zahra', 'Hamza', 'Sara', 'Osman'],
    'department': ['SEECS', 'SADA', 'SEECS', 'NBS', 'SMME'],
    'interests': ['Artificial Intelligence', 'Digital Design', 'Machine Learning', 'Business Growth', 'Robotics and Automation'],
    'registered_events': ['Speed Programming', 'Poster Design', 'Capture the Flag', 'Business Plan', 'RoboWars']
}
df = pd.DataFrame(data)

# 2. Semantic Profile Creation
df['rich_profile'] = "Dept: " + df['department'] + " | Interests: " + df['interests']

# 3. Load Transformer Model (Understanding AI vs ML)
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(df['rich_profile'].tolist())

# 4. Calculate Similarity & Convert to Native Float for JSON compatibility
sim_matrix = cosine_similarity(embeddings).astype(float)

# 5. Optimization: Find Top 2 Matches for EVERYONE
def get_top_matches(user_idx, top_n=2):
    user_scores = sim_matrix[user_idx]
    # argsort returns indices in ascending order
    # The highest score is 1.0 (the user themselves), so we take the two indices before the last one
    best_indices = np.argsort(user_scores)[-(top_n + 1):-1][::-1]
    return [(idx, user_scores[idx]) for idx in best_indices]

print("Semantic scores optimized. Ali and Hamza now have high similarity (AI/ML)!")

from pyvis.network import Network
import IPython

def draw_optimized_graph(df, sim_matrix):
    net = Network(notebook=True, height="500px", width="100%", bgcolor="#ffffff", cdn_resources='remote')
    colors = {'SEECS': '#27ae60', 'SADA': '#e67e22', 'NBS': '#f1c40f', 'SMME': '#2980b9'}

    for i, row in df.iterrows():
        net.add_node(i, label=row['name'], title=f"{row['department']}: {row['interests']}",
                     color=colors.get(row['department'], '#7f8c8d'), size=25)

    # Only draw edges for the Top 2 matches per person to keep the UI clean
    for i in range(len(df)):
        top_2 = get_top_matches(i)
        for match_idx, score in top_2:
            net.add_edge(i, int(match_idx), value=score, title=f"{int(score*100)}% Match", color="#bdc3c7")

    net.force_atlas_2based() # This layout pulls similar nodes into clusters
    net.show("nust_smart_network.html")
    return IPython.display.HTML("nust_smart_network.html")

draw_optimized_graph(df, sim_matrix)

def website_match_notification():
    for user_idx in range(len(df)):
        user_name = df.iloc[user_idx]['name']
        top_2 = get_top_matches(user_idx)

        print(f"--- 📬 WEBSITE NOTIFICATION FOR: {user_name} ---")

        for rank, (match_idx, score) in enumerate(top_2, 1):
            match_user = df.iloc[match_idx]
            match_pct = int(score * 100)

            # Smart reasoning for the notification
            common_dept = df.iloc[user_idx]['department'] == match_user['department']
            reason = "common departmental background" if common_dept else "highly aligned semantic interests"

            print(f"Recommendation #{rank}: Meet {match_user['name']}!")
            print(f"Match Score: {match_pct}% based on {reason}.")
            print(f"Message: 'Hi {user_name}, we think you'd enjoy connecting with {match_user['name']} regarding {match_user['interests']}.'")
            print(f"Starter: 'Hey {match_user['name']}, I saw we're both attending the Olympiad. Want to sync up?'")
        print("\n")

website_match_notification()