# Generated by Django 5.2.11 on 2026-02-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olympiad_core', '0001_initial'),
        ('registrations', '0001_initial'),
        ('societies', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('sport_type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('mixed', 'Mixed')], max_length=50)),
                ('rules_document', models.FileField(blank=True, null=True, upload_to='sport_rules/')),
                ('max_participants', models.IntegerField(default=50)),
                ('min_team_size', models.IntegerField(default=1)),
                ('max_team_size', models.IntegerField(default=15)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event_date', models.DateTimeField()),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='sport_banners/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='sports', to='olympiad_core.category')),
                ('collaborating_societies', models.ManyToManyField(blank=True, related_name='collaborated_sports', to='societies.society')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='olympiad_core.olympiad')),
                ('organizing_society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_sports', to='societies.society')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports', to='venues.venue')),
            ],
            options={
                'ordering': ['event_date'],
                'unique_together': {('olympiad', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SportMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=50)),
                ('team_a_score', models.IntegerField(blank=True, null=True)),
                ('team_b_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sports.sport')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='registrations.team')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='registrations.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_matches', to='venues.venue')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='registrations.team')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='SportRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('medal', models.CharField(blank=True, choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=50, null=True)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='sports.sport')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_rankings', to='registrations.team')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('sport', 'team')},
            },
        ),
    ]
