# Generated by Django 5.2.11 on 2026-02-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('modules', '0001_initial'),
        ('olympiad_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registered_teams', models.IntegerField(default=0)),
                ('total_registered_members', models.IntegerField(default=0)),
                ('teams_participated', models.IntegerField(default=0)),
                ('members_participated', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('completed_matches', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('unique_organizations', models.IntegerField(default=0)),
                ('gender_distribution', models.JSONField(blank=True, default=dict)),
                ('age_distribution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEngagementScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_score', models.FloatField(default=0)),
                ('attendance_score', models.FloatField(default=0)),
                ('interaction_score', models.FloatField(default=0)),
                ('networking_score', models.FloatField(default=0)),
                ('learning_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_registrations', models.IntegerField(default=0)),
                ('daily_active_users', models.IntegerField(default=0)),
                ('sessions_attended', models.IntegerField(default=0)),
                ('polls_created', models.IntegerField(default=0)),
                ('qna_questions', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('connections_made', models.IntegerField(default=0)),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='olympiad_core.olympiad')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registered', models.IntegerField(default=0)),
                ('total_attended', models.IntegerField(default=0)),
                ('no_show_count', models.IntegerField(default=0)),
                ('average_session_duration', models.FloatField(default=0, help_text='In minutes')),
                ('engagement_score', models.FloatField(default=0, help_text='0.0-1.0')),
                ('total_polls_created', models.IntegerField(default=0)),
                ('total_poll_responses', models.IntegerField(default=0)),
                ('total_qna_questions', models.IntegerField(default=0)),
                ('total_feedback_responses', models.IntegerField(default=0)),
                ('connections_made', models.IntegerField(default=0)),
                ('card_exchanges', models.IntegerField(default=0)),
                ('demographics_data', models.JSONField(blank=True, default=dict, help_text='Age, gender, industry distributions')),
                ('overall_sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=50)),
                ('average_satisfaction_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registered_teams', models.IntegerField(default=0)),
                ('total_registered_members', models.IntegerField(default=0)),
                ('teams_participated', models.IntegerField(default=0)),
                ('members_participated', models.IntegerField(default=0)),
                ('average_team_score', models.FloatField(default=0)),
                ('highest_team_score', models.FloatField(default=0)),
                ('unique_organizations', models.IntegerField(default=0)),
                ('gender_distribution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='modules.module')),
            ],
        ),
        migrations.CreateModel(
            name='OlympiadAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registrations', models.IntegerField(default=0)),
                ('total_participants', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('total_modules', models.IntegerField(default=0)),
                ('total_sports', models.IntegerField(default=0)),
                ('total_check_ins', models.IntegerField(default=0)),
                ('attendance_rate', models.FloatField(default=0, help_text='Percentage 0-100')),
                ('total_connections', models.IntegerField(default=0)),
                ('avg_connections_per_user', models.FloatField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overall_satisfaction', models.FloatField(default=0, help_text='Average rating 1-5')),
                ('nps_score', models.IntegerField(blank=True, help_text='Net Promoter Score -100 to 100', null=True)),
                ('total_unique_organizations', models.IntegerField(default=0)),
                ('gender_distribution', models.JSONField(blank=True, default=dict)),
                ('geographic_distribution', models.JSONField(blank=True, default=dict)),
                ('hashtag_mentions', models.IntegerField(default=0)),
                ('social_engagement_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olympiad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='olympiad_core.olympiad')),
            ],
        ),
    ]
