# Generated by Django 5.2.11 on 2026-02-10 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('modules', '0001_initial'),
        ('olympiad_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, help_text='JSON array of recommended sessions/modules with timing')),
                ('generation_reason', models.TextField(blank=True)),
                ('algorithm_version', models.CharField(default='v1', max_length=50)),
                ('user_satisfaction', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olympiad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalized_agendas', to='olympiad_core.olympiad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_agenda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('session', 'Session Recommendation'), ('module', 'Module Recommendation'), ('connection', 'Connection Recommendation')], max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=255)),
                ('relevance_score', models.IntegerField(choices=[(1, '1 - Not relevant'), (2, '2 - Somewhat relevant'), (3, '3 - Relevant'), (4, '4 - Very relevant'), (5, '5 - Perfect')])),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Recommendation score 0.0-1.0')),
                ('reason', models.CharField(choices=[('skill_level', 'Matches skill level'), ('interest', 'Matches interests'), ('performance', 'Based on past performance')], max_length=255)),
                ('was_viewed', models.BooleanField(default=False)),
                ('was_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='SessionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Recommendation score 0.0-1.0')),
                ('reason', models.CharField(choices=[('interest_match', 'Matches your interests'), ('collaborative_filtering', 'Users like you attended'), ('trending', 'Trending session'), ('speaker_follow', 'By followed speaker')], max_length=255)),
                ('was_clicked', models.BooleanField(default=False)),
                ('was_attended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='events.eventsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user', 'session')},
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('view_session', 'Viewed Session'), ('register_session', 'Registered for Session'), ('attend_session', 'Attended Session'), ('view_profile', 'Viewed Profile'), ('connect_request', 'Connection Request'), ('view_module', 'Viewed Module'), ('view_sport', 'Viewed Sport')], max_length=50)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('engagement_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='recommendat_user_id_df07ee_idx'), models.Index(fields=['-created_at'], name='recommendat_created_451b0f_idx')],
            },
        ),
    ]
