# Generated by Django 5.2.11 on 2026-02-10 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olympiad_core', '0001_initial'),
        ('societies', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.JSONField(default=list, help_text='JSON array of expertise areas')),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('module_type', models.CharField(choices=[('technical', 'Technical'), ('non_technical', 'Non-Technical')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('rules_document', models.FileField(blank=True, null=True, upload_to='module_rules/')),
                ('max_participants', models.IntegerField(default=100)),
                ('min_team_size', models.IntegerField(default=1)),
                ('max_team_size', models.IntegerField(default=5)),
                ('participation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event_date', models.DateTimeField()),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='module_banners/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='modules', to='olympiad_core.category')),
                ('collaborating_societies', models.ManyToManyField(blank=True, related_name='collaborated_modules', to='societies.society')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='olympiad_core.olympiad')),
                ('organizing_society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_modules', to='societies.society')),
            ],
            options={
                'ordering': ['event_date'],
                'unique_together': {('olympiad', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ModuleRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('round_type', models.CharField(choices=[('preliminary', 'Preliminary'), ('semi_final', 'Semi-Final'), ('final', 'Final'), ('qualifying', 'Qualifying')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_advancement', models.IntegerField(blank=True, help_text='Teams advancing to next round', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='modules.module')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_rounds', to='venues.venue')),
            ],
            options={
                'ordering': ['order', 'start_time'],
                'unique_together': {('module', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoundJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_assignments', to='modules.judge')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='modules.moduleround')),
            ],
            options={
                'unique_together': {('round', 'judge')},
            },
        ),
    ]
