# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SoQojPWpSGvt-NqYT3jyKeQj_GS9BTu0
"""

import pandas as pd

# Data as a list of dictionaries
data = [
    {"question": "What is the University Olympiad?", "answer": "The University Olympiad is a multi-day event consisting of technical, non-technical, and sports competitions organized by different university societies in collaboration with the central Olympiad society."},
    {"question": "Who organizes the Olympiad?", "answer": "The Olympiad is centrally governed by the Olympiad Society and individual modules are managed by respective university societies."},
    {"question": "What types of events are included in the Olympiad?", "answer": "The Olympiad includes technical modules, non-technical modules, and sports events."},
    {"question": "What is a module in the Olympiad?", "answer": "A module is a category of events such as a technical competition, non-technical contest, or sports event managed by a specific society."},
    {"question": "Who can create events in the system?", "answer": "Only Society Admins or authorized Event Heads can create and manage events."},
    {"question": "What is the role of the Olympiad Core Team?", "answer": "The Olympiad Core Team acts as Super Admin and oversees all societies, events, and platform configurations."},
    {"question": "How does participant registration work?", "answer": "Participants register online through dynamic forms, select tickets, and receive a QR code confirmation."},
    {"question": "What is early bird registration?", "answer": "Early bird registration offers discounted pricing for participants who register before a defined deadline."},
    {"question": "What happens if an event is full?", "answer": "If an event reaches capacity, new registrants are added to a waitlist automatically."},
    {"question": "How is entry managed at the venue?", "answer": "Entry is managed using QR code check-in which can work both online and offline."},
    {"question": "What departments exist in a module?", "answer": "Each module may include Management, Registration, Security, Marketing, Logistics, and Technical Operations departments."},
    {"question": "What is the responsibility of the Registration department?", "answer": "The Registration department manages participant registrations, tickets, waitlists, and attendance verification."},
    {"question": "What does the Security department handle?", "answer": "The Security department handles access control, QR validation, and incident reporting."},
    {"question": "How are sessions scheduled?", "answer": "Sessions are scheduled using a drag-and-drop scheduler with automatic conflict detection."},
    {"question": "What is AI-based attendee matching?", "answer": "AI-based attendee matching recommends participants to connect based on interests, roles, and goals."},
    {"question": "What is the event chatbot used for?", "answer": "The chatbot answers questions related to schedule, venue, speakers, and general event logistics."},
    {"question": "Can attendees get a personalized agenda?", "answer": "Yes, the system generates a personalized agenda based on attendee interests and preferences."},
    {"question": "What is the venue floor plan feature?", "answer": "It is an interactive visual map showing seating, booths, and capacity information."},
    {"question": "How are badges generated?", "answer": "Badges are generated using a custom badge designer with dynamic fields and exported as PDFs."},
    {"question": "What happens if internet is unavailable at the venue?", "answer": "The system supports offline check-in and syncs data once the internet is restored."}
]

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("nust_olympiad_faq.csv", index=False)

print("CSV file created: nust_olympiad_faq.csv")

import os
import pandas as pd
from getpass import getpass

# Imports for Groq and Vector Store
from langchain_groq import ChatGroq
from langchain_chroma import Chroma
from langchain_community.embeddings import HuggingFaceInstructEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# Securely set the Groq API Key
if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass("Enter your Groq API Key: ")

# 1. Load and Embed as usual
df = pd.read_csv("nust_olympiad_faq.csv")
documents = [f"Q: {row['question']}\nA: {row['answer']}" for _, row in df.iterrows()]

embedding_model = HuggingFaceInstructEmbeddings(
    model_name="hkunlp/instructor-large",
    model_kwargs={'device': 'cpu'}
)

vectordb = Chroma.from_texts(
    texts=documents,
    embedding=embedding_model,
    persist_directory="./chroma_db"
)
base_retriever = vectordb.as_retriever(search_kwargs={"k": 3})

# 2. Manual "Thinking" Step (Multi-Query replacement)
# This uses the LLM to generate 3 variations of the question manually.
from langchain_core.prompts import PromptTemplate

query_generation_prompt = PromptTemplate(
    input_variables=["question"],
    template="""Generate 3 different versions of the following user question to retrieve
    the best results from a vector database. Provide them separated by newlines.
    Original question: {question}"""
)

# We'll use this inside the chain in the next cell!
print("Smarter Retrieval logic (Manual Multi-Query) is set up!")

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# 1. Main Reasoning LLM
llm = ChatGroq(model_name="llama-3.3-70b-versatile", temperature=0.2)

# 2. Reasoning Prompt
template = """You are the NUST Olympiad Assistant.
Analyze the context below to answer the user's question.

Guidelines:
- If the answer isn't a 100% exact word match but the meaning is there, answer it.
- Use the context to reason.
- Only say "I’m sorry, I don’t have information on that topic. Please ask about the NUST Olympiad event or related modules" if the context is completely irrelevant.

Context: {context}
Question: {question}
Answer:"""

prompt = ChatPromptTemplate.from_template(template)

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

# 3. Chain
rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

print("Bot Ready! Type 'exit' to stop.")
while True:
    user_input = input("You: ")
    if user_input.lower() in ["exit", "quit"]: break
    print(f"Bot: {rag_chain.invoke(user_input)}\n")