# Generated by Django 5.2.11 on 2026-02-10 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='Pakistan', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('total_capacity', models.IntegerField()),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('floor_plan', models.FileField(blank=True, null=True, upload_to='floor_plans/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VenueSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('space_type', models.CharField(choices=[('auditorium', 'Auditorium'), ('classroom', 'Classroom'), ('workshop_room', 'Workshop Room'), ('breakout_room', 'Breakout Room'), ('office', 'Office'), ('lounge', 'Lounge'), ('dining', 'Dining Area'), ('outdoor', 'Outdoor')], max_length=50)),
                ('capacity', models.IntegerField()),
                ('floor', models.IntegerField(default=1)),
                ('layout_data', models.JSONField(blank=True, default=dict, help_text='SVG layout and seat/booth data')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='venues.venue')),
            ],
            options={
                'ordering': ['floor', 'name'],
                'unique_together': {('venue', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20)),
                ('seating_type', models.CharField(choices=[('seat', 'Seat'), ('booth', 'Booth'), ('zone', 'Zone'), ('standing', 'Standing Area')], default='seat', max_length=50)),
                ('row', models.CharField(max_length=10)),
                ('column', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=50)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('x_coordinate', models.FloatField(blank=True, null=True)),
                ('y_coordinate', models.FloatField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_seats', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating', to='venues.venuespace')),
            ],
            options={
                'ordering': ['row', 'column'],
                'unique_together': {('space', 'seat_number')},
            },
        ),
    ]
